### ISSUE TITLE
Improve file layout?

### ISSUE THREAD

**Issue by tripu** [w3c/i18n-checker#56]
- Move `tests/` under `www/`, so that tests can be served without additional configuration in the server.
- Move `tests/*.properties` to `conf/` to avoid exposing internal config or details to clients accidentally.

h/t @vivienlacourba.

**Comment by r12a** [comment]
changed to new label, admin, so that we can keep 'enhancement' for new checker features

**Comment by r12a** [comment]
i'm ok with the principle. Here are some slightly different suggestions though.

- move `tests/index.php` under `www/` and rename to `tests.php`
- leave `tests/*.properties` where they are (with `generate.php`, `data.php` and `non-nfc.php`) so that all test related stuff other than the user visible `test.php` is neatly gathered in one clearly labelled place (note that there are no sensitive internal config details in the these files - they just list which tests to run and what the expected outcome is)

does that work?

**Comment by r12a** [comment]
i tried it out in a copy of the i18n-checker directory (ie. moved `tests/index.php` to `www/test.php`).  The only thing i needed to change to make it work was:

in `src/class.Test.php` add `$fileName = "../tests/".$fileName;` after line 31

**Comment by vivienlacourba** [comment]
@r12a this looks good to me.

**Comment by tripu** [comment]
:+1:

**Comment by tripu** [comment]
Closed by @r12a in #70.
